[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.setuptools', 'gcc', 'pkg-config']

[phases.install]
cmds = [
    'python3.11 -m pip install --upgrade pip',
    'python3.11 -m pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'echo "Build completed"'
]

[start]
cmd = 'python3.11 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT'

[variables]
PYTHON_VERSION = '3.11'
PYTHONPATH = '/app'